### PR TITLE
Feature Flags: Cleaning up!

### PR DESCRIPTION
**Pull request by janorivera**
## Description

Updating defaults
Cleaning up helpline configurations

I'll post the plans soon
### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Other Related Issues

None

### AFTER YOU MERGE

1. Cut a release tag using the Github workflow. Wait for it to complete and notify in the #aselo-deploys Slack channel.
2. Comment on the ticket with the release tag version AND any additional instructions required to configure an environment to test the changes.
3. Only then move the ticket into the QA column in JIRA

You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the following confusion is on you! :-P

### CODE REVIEW

**Review by stephenhand — APPROVED** [review]
Thank you!

**Comment by janorivera** [comment]
STG PLAN for all accounts:

Environment: staging
Helpline Code: as
Account SID: AC1ca120bc71593bbe9ca78e2232a31e0d

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False

------------------
Environment: staging
Helpline Code: br
Account SID: AC4a92fba4d8040b1d6dbe2bbceee87cbf

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_save_insights from True to False

------------------
Environment: staging
Helpline Code: ca
Account SID: ACeb335f4685aa874fddf00cdd7c2946bd

Plan:
Remove ui_attributes.theme with value {'isLight': True}

------------------
Environment: staging
Helpline Code: cl
Account SID: AC6ca34b61e7bf2d7cf8b8ca24e7efe65f

Plan:
Update attributes.feature_flags.enable_aselo_messaging_ui from True to False
Update attributes.feature_flags.enable_twilio_transcripts from True to False

------------------
Environment: staging
Helpline Code: co
Account SID: AC76b8bd2798b01b067a1be7f17d36c894

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_lex from True to False
Update attributes.feature_flags.enable_save_insights from True to False

------------------
Environment: staging
Helpline Code: et
Account SID: ACfd932bd76669f9cc2145e67e6c3e03ea

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_save_insights from True to False
Update attributes.feature_flags.post_survey_serverless_handled from False to True

------------------
Environment: staging
Helpline Code: hu
Account SID: ACbdbee34ef7d099e71cf095d540ff3270

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_save_insights from True to False
Update attributes.feature_flags.post_survey_serverless_handled from False to True

------------------
Environment: staging
Helpline Code: in
Account SID: AC3ee345e8fe8213010ff81fbe54b1414e

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_save_insights from True to False

------------------
Environment: staging
Helpline Code: jm
Account SID: ACbc27263c18e621f3deb57cf1998a4e04

Plan:
Remove attributes.feature_flags.enable_transcripts with value True
Update attributes.feature_flags.enable_client_profiles from False to True
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_save_insights from True to False

------------------
Environment: staging
Helpline Code: mt
Account SID: ACfb0ccf10880289d67f5c4e85ae26402b

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Update attributes.feature_flags.enable_save_insights from True to False
Update attributes.feature_flags.post_survey_serverless_handled from False to True

------------------
Environment: staging
Helpline Code: mw
Account SID: AC874af45ec4a696d5d4dca07b0036e2bf

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_save_insights from True to False
Update attributes.feature_flags.post_survey_serverless_handled from False to True

------------------
Environment: staging
Helpline Code: nz
Account SID: AC3ee873a0431086e5b1166db5f5e29860

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Remove attributes.feature_flags.enable_resources with value False

------------------
Environment: staging
Helpline Code: ph
Account SID: ACa10989d583df770649051aee1430fce9

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_external_transcripts from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_save_insights from True to False
Update attributes.feature_flags.post_survey_serverless_handled from False to True

------------------
Environment: staging
Helpline Code: sg
Account SID: ACa00e3e32f7ba405cc0f5906906d88e97

Plan:
Update attributes.feature_flags.enable_conferencing from True to False
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False

------------------
Environment: staging
Helpline Code: th
Account SID: AC58ec02594f3ca5225db71913b1cda612

Plan:
Update attributes.feature_flags.enable_aselo_messaging_ui from False to True
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_csam_report from True to False
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_save_insights from True to False

------------------
Environment: staging
Helpline Code: uk
Account SID: AC542ee9a6613ce5ff976d075a3e3bd38d

Plan:
Remove attributes.feature_flags.enable_transcripts with value True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.enable_post_survey from True to False

------------------
Environment: staging
Helpline Code: za
Account SID: AC16dd71c6fd135ee250bd213ad1efa2e8

Plan:
Remove attributes.feature_flags.enable_transcripts with value True
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Update attributes.feature_flags.post_survey_serverless_handled from False to True

------------------
Environment: staging
Helpline Code: zm
Account SID: ACc59300c7ca018e8652e4d6d86c2d50e6

Plan:
Remove attributes.feature_flags.enable_transcripts with value True
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_save_insights from True to False

------------------
Environment: staging
Helpline Code: zw
Account SID: AC48d146ce2460184b8944cc7fdf8c5d25

Plan:
Remove attributes.feature_flags.enable_transcripts with value True
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_save_insights from True to False

**Comment by nickhurlburt** [comment]
@janorivera those look like some non-trivial changes. For this cleanup PR, is it expected that there are no helpline-facing changes?

**Comment by janorivera** [comment]
PRODUCTION PLAN:

------------------
Environment: production
Helpline Code: as
Account SID: AC4858840776b1f98a1367c9c6a401bd2c

Plan:
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Remove attributes.feature_flags.enable_resources with value True

------------------
Environment: production
Helpline Code: br
Account SID: AC98b66f5541f81de7050c7254cf5c96c9

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: ca
Account SID: AC9f951863c83dc61cf94bdc12a12270a5

Plan:
No changes.

------------------
Environment: production
Helpline Code: cl
Account SID: AC13e88b6577da29a0b35c0ea7939c3c22

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Remove attributes.feature_flags.enable_resources with value False

------------------
Environment: production
Helpline Code: co
Account SID: AC520ec62dcfa4ab4105c2f5850caf52b0

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: et
Account SID: AC16aa1fb9123860efd3bdde74de556e21

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: hu
Account SID: AC378f491732fc29691b4126a2287cea9a

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_fullstory_monitoring from False to True

------------------
Environment: production
Helpline Code: in
Account SID: AC64efffad72dccd812ca0c156355217ed

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: jm
Account SID: AC9fd261078d40fcfa06f0e374921af7a5

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Add attributes.contacts_waiting_channels with value ['voice', 'web', 'whatsapp', 'facebook', 'instagram']
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: mt
Account SID: AC7854f6126459347434a8e659295ebb79

Plan:
Update attributes.feature_flags.post_survey_serverless_handled from False to True
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: mw
Account SID: AC926d9077405d7f5b4c7129d3087d7814

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: nz
Account SID: AC2825ea172ea83c2e422a9772a27beb29

Plan:
Remove attributes.feature_flags.enable_transcripts with value False
Remove attributes.feature_flags.enable_resources with value False

------------------
Environment: production
Helpline Code: ph
Account SID: ACd9d59ab87f24d9086b25a7e3c67b2231

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_fullstory_monitoring from False to True
Remove attributes.feature_flags.enable_transcripts with value False
Remove attributes.feature_flags.enable_resources with value False

------------------
Environment: production
Helpline Code: sg
Account SID: AC0751f021d17d50f0ee5af094acdee7c8

Plan:
Update attributes.config_flags.enableExternalRecordings from False to True
Update attributes.feature_flags.enable_conferencing from True to False
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_voice_recordings from False to True
Add attributes.external_recordings_enabled with value True
Remove attributes.feature_flags.external_recordings_enabled with value True

------------------
Environment: production
Helpline Code: th
Account SID: AC77e853192a62159196decc2468243518

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False

------------------
Environment: production
Helpline Code: za
Account SID: AC988e78b713be4a04246b39835de37ad4

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: zm
Account SID: ACf0b04d307d8f20074dc09cdb3b4f0a83

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Remove attributes.feature_flags.enable_transcripts with value False

------------------
Environment: production
Helpline Code: zw
Account SID: ACd0db81cffec7eb658f6ee176a06dc902

Plan:
Update attributes.feature_flags.enable_counselor_toolkits from False to True
Update attributes.feature_flags.enable_twilio_transcripts from True to False
Update attributes.feature_flags.enable_save_insights from True to False
Remove attributes.feature_flags.enable_transcripts with value True

**Comment by janorivera** [comment]
@nickhurlburt  Yes, this is something that I want to confirm with @stephenhand  as well.

I spoke with @dee-luo as well on some this changes, things discussed:

General changes:

1. enable_counselor_toolkits  can be set to TRUE as default for all accounts.
2.  Since enable_external_transcripts is TRUE for all helplines, then we can set enable_twilio_transcripts to FALSE for all helplines (is this right @stephenhand ?)
3. enable_fullstory_monitoring  should be TRUE for all accounts
4. enable_save_insights  should be set to FALSE for all staging account unless we enable it explicitly like for CA or NZ.
5. enable_transcripts and enable_resources  are deprecated, we should remove them.
6. post_survey_serverless_handled  should be set to TRUE for all helplines, I think this is was the intention right? 


Specific changes:

CL is trying disabling enable_aselo_messaging_ui and see how it goes.
JM is enabling client profiles on STG
SG configurations for voice recordings on PROD.

**Review by stephenhand — APPROVED** [review]

**Pull request merged**
