### PR TITLE
CHI-863: Add Full Story element identifiers

### PR DESCRIPTION
**Pull request by stephenhand**
* Added requested identifiers as `data-fs-id` attributes, to keep them separate from HTML IDs and reduce the chance of developers breaking them with updates
* Used naming convention `Category-ElementFunction-ControlType` where Category would be a high level functional area like 'Contact' or 'Case', ElementFunction would be what the element is supposed to do 'EndCallOrChat', 'Transfer', and ControlType is what the control is, 'Button', 'DropDown' etc.
* Changed some linter settings to not get upset about windows line endings.

There are 2 elements specified in CHI-863 that have not had attributes explicitly added to them: 
* The 'Accept' button, this is not part of our plugin but part of the Twlio core UI. There is not a simple reliable wauy of adding extra attributes to this markup as far as we are aware. The suggested alternative would be to use a class based CSS selector for the event capturing clicks of these buttons in Full Story - `button.Twilio-TaskButton-Accept` and `button.Twilio-IncomingTask-Accept` for the All Tasks panel and Incoming Task panel versions of this button respectively 
TODO - add data element to 'Accept' button, which is defined in flex rather than the plugin

### CODE REVIEW

**Review by nickhurlburt — APPROVED** [review]
Looks good to me, though it'd be good to get a review from Murilo or Gian.

(Note: we will often list a Primary Reviewer in the PR description to make it clear who needs to review, and this is a good practice now that we have more people.)

One thing to note is that one missing thing from the issue is the End Chat button:
image

This is a Twilio button like the Accept button, so we probably just need the Twilio ID for it, rather than adding our own.

**Comment by stephenhand** [comment]
Looks like we can select the 'End Call / Chat' button with `button.Twilio-TaskCanvasHeader-EndButton`

**Comment by nickhurlburt** [comment]
Let's try to get this merged and deployed to Development before the team meeting tomorrow, to enable Jana to start working with it. A second review would be good to do before then, but not strictly necessary.

**Comment by GPaoloni** [comment]
Looks good to me!

**Pull request merged**
