### PR TITLE
Dee ca updates 0717

### PR DESCRIPTION
**Pull request by dee-luo**
-Updates to webchat flow to check counsellors in queue
-Adding testing call type
-Fix edge case where no language parameter is passed in test chat
-Add TaskRouter filter steps for G2T NS
-Add G2T NS Phone Numbers
-Remove 1-7 upset level requirement, add "Chat Only" to name
-Remove local staging numbers for G2TON and use for G2T NS
-Add G2TNS Studio Flows to staging and production, update channel vars
-Update Issue Tags to reflect "Other" 
-Add Abuse Details to summary tab 
-Remove Interpreter queue logic from G2T NS flow
-Add new recording for Fr to English queue switch, adjust studio flows

### CODE REVIEW

**Comment by janorivera** [comment]
TG PLAN FOR CONFIGURE


Terraform will perform the following actions:

  # module.channel.twilio_studio_flows_v2.channel_studio_flow["g2tns"] will be created
  + resource "twilio_studio_flows_v2" "channel_studio_flow" {
      + commit_message = (known after apply)
      + definition     = jsonencode(
            {
              + description   = "Good2Talk NS IVR"
              + flags         = {
                  + allow_concurrent_calls = true
                }
              + initial_state = "Trigger"
              + states        = [
                  + {
                      + name        = "Trigger"
                      + properties  = {
                          + offset = {
                              + x = -550
                              + y = -780
                            }
                        }
                      + transitions = [
                          + {
                              + event = "incomingMessage"
                            },
                          + {
                              + event = "incomingCall"
                              + next  = "split_keys_lang"
                            },
                          + {
                              + event = "incomingConversationMessage"
                            },
                          + {
                              + event = "incomingRequest"
                            },
                          + {
                              + event = "incomingParent"
                            },
                        ]
                      + type        = "trigger"
                    },
                  + {
                      + name        = "split_keys_lang"
                      + properties  = {
                          + input  = "{{trigger.call.To}}"
                          + offset = {
                              + x = -590
                              + y = -540
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{trigger.call.To}}",
                                        ]
                                      + friendly_name = "If value contains en_number"
                                      + type          = "contains"
                                      + value         = "5878043655"
                                    },
                                ]
                              + event      = "match"
                              + next       = "Msg10006E-InfoMessage2"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{trigger.call.To}}",
                                        ]
                                      + friendly_name = "If value contains fr_number"
                                      + type          = "contains"
                                      + value         = "5878044316"
                                    },
                                ]
                              + event      = "match"
                              + next       = "Msg10006F-InfoMessage2"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "sendToQ6001_English"
                      + properties  = {
                          + attributes    = jsonencode(
                                {
                                  + channelType        = "voice"
                                  + ignoreAgent        = ""
                                  + language           = "en-CA"
                                  + name               = "{{trigger.call.From}}"
                                  + transferTargetType = ""
                                  + type               = "inbound"
                                }
                            )
                          + channel       = "TCdc0e5fe0a16adeb44d364645c69fe2f1"
                          + offset        = {
                              + x = -1620
                              + y = 1060
                            }
                          + waitUrl       = "https://twilio-service-4854.twil.io/6015_g2tns_english"
                          + waitUrlMethod = "GET"
                          + workflow      = "WWf88dc2e079f1c57fb3f98753d6121b79"
                        }
                      + transitions = [
                          + {
                              + event = "callComplete"
                            },
                          + {
                              + event = "failedToEnqueue"
                            },
                          + {
                              + event = "callFailure"
                            },
                        ]
                      + type        = "send-to-flex"
                    },
                  + {
                      + name        = "sendToQ6002_French"
                      + properties  = {
                          + attributes    = jsonencode(
                                {
                                  + channelType        = "voice"
                                  + ignoreAgent        = ""
                                  + language           = "fr-CA"
                                  + name               = "{{trigger.call.From}}"
                                  + transferTargetType = ""
                                  + type               = "inbound"
                                }
                            )
                          + channel       = "TCdc0e5fe0a16adeb44d364645c69fe2f1"
                          + offset        = {
                              + x = -320
                              + y = 1190
                            }
                          + waitUrl       = "https://twilio-service-4854.twil.io/6016_g2tns_french"
                          + waitUrlMethod = "GET"
                          + workflow      = "WWf88dc2e079f1c57fb3f98753d6121b79"
                        }
                      + transitions = [
                          + {
                              + event = "callComplete"
                            },
                          + {
                              + event = "failedToEnqueue"
                            },
                          + {
                              + event = "callFailure"
                            },
                        ]
                      + type        = "send-to-flex"
                    },
                  + {
                      + name        = "Msg10006E-InfoMessage2"
                      + properties  = {
                          + finish_on_key    = "#"
                          + gather_language  = "en"
                          + language         = "en-CA"
                          + loop             = 1
                          + offset           = {
                              + x = -1080
                              + y = -190
                            }
                          + play             = "https://twilio-service-4854.twil.io/Msg10006G2TONEn.mp3"
                          + profanity_filter = "true"
                          + speech_timeout   = "auto"
                          + stop_gather      = true
                          + timeout          = 2
                        }
                      + transitions = [
                          + {
                              + event = "keypress"
                              + next  = "split_keys_E"
                            },
                          + {
                              + event = "speech"
                            },
                          + {
                              + event = "timeout"
                              + next  = "Msg60011E-Inflight"
                            },
                        ]
                      + type        = "gather-input-on-call"
                    },
                  + {
                      + name        = "Msg10010E-PrivacyMsg"
                      + properties  = {
                          + language = "en-CA"
                          + loop     = 1
                          + offset   = {
                              + x = -1890
                              + y = 170
                            }
                          + play     = "https://twilio-service-4854.twil.io/G2TEnPrivacy.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "Msg60011E-Inflight"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "Msg10015E-ToS"
                      + properties  = {
                          + language = "en-CA"
                          + loop     = 1
                          + offset   = {
                              + x = -1580
                              + y = 250
                            }
                          + play     = "https://twilio-service-4854.twil.io/G2TENToS.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "Msg60011E-Inflight"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "Msg60011E-Inflight"
                      + properties  = {
                          + language = "en-CA"
                          + loop     = 1
                          + offset   = {
                              + x = -1650
                              + y = 700
                            }
                          + play     = "https://twilio-service-4854.twil.io/Msg60011E.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "sendToQ6001_English"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "split_keys_E"
                      + properties  = {
                          + input  = "{{widgets.Msg10006E-InfoMessage2.Digits}}"
                          + offset = {
                              + x = -1550
                              + y = -40
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "en_set_retry"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{widgets.Msg10006E-InfoMessage2.Digits}}",
                                        ]
                                      + friendly_name = "If value equal_to 5"
                                      + type          = "equal_to"
                                      + value         = "5"
                                    },
                                ]
                              + event      = "match"
                              + next       = "Msg10010E-PrivacyMsg"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{widgets.Msg10006E-InfoMessage2.Digits}}",
                                        ]
                                      + friendly_name = "If value equal_to 6"
                                      + type          = "equal_to"
                                      + value         = "6"
                                    },
                                ]
                              + event      = "match"
                              + next       = "Msg10015E-ToS"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "Msg10006F-InfoMessage2"
                      + properties  = {
                          + finish_on_key    = "#"
                          + gather_language  = "en"
                          + language         = "fr-CA"
                          + loop             = 1
                          + offset           = {
                              + x = -180
                              + y = -210
                            }
                          + play             = "https://twilio-service-4854.twil.io/Msg10006G2TFr.mp3"
                          + profanity_filter = "true"
                          + speech_timeout   = "auto"
                          + stop_gather      = true
                          + timeout          = 2
                          + voice            = "alice"
                        }
                      + transitions = [
                          + {
                              + event = "keypress"
                              + next  = "split_keys_F"
                            },
                          + {
                              + event = "speech"
                            },
                          + {
                              + event = "timeout"
                              + next  = "InflightMessage-F"
                            },
                        ]
                      + type        = "gather-input-on-call"
                    },
                  + {
                      + name        = "split_keys_F"
                      + properties  = {
                          + input  = "{{widgets.Msg10006F-InfoMessage2.Digits}}"
                          + offset = {
                              + x = 300
                              + y = -150
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "set_retry_fr"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{widgets.Msg10006F-InfoMessage2.Digits}}",
                                        ]
                                      + friendly_name = "If value equal_to 5"
                                      + type          = "equal_to"
                                      + value         = "5"
                                    },
                                ]
                              + event      = "match"
                              + next       = "Msg10010F-PrivacyMsg"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{widgets.Msg10006F-InfoMessage2.Digits}}",
                                        ]
                                      + friendly_name = "If value equal_to 6"
                                      + type          = "equal_to"
                                      + value         = "6"
                                    },
                                ]
                              + event      = "match"
                              + next       = "Msg10015F-ToS"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "InflightMessage-F"
                      + properties  = {
                          + language = "fr-CA"
                          + loop     = 1
                          + offset   = {
                              + x = -130
                              + y = 520
                            }
                          + play     = "https://twilio-service-4854.twil.io/Msg60021.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "check_before_queue"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "Msg10010F-PrivacyMsg"
                      + properties  = {
                          + language = "fr-CA"
                          + loop     = 1
                          + offset   = {
                              + x = 410
                              + y = 180
                            }
                          + play     = "https://twilio-service-4854.twil.io/G2TFrPrivacy.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "InflightMessage-F"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "Msg10015F-ToS"
                      + properties  = {
                          + language = "fr-CA"
                          + loop     = 1
                          + offset   = {
                              + x = 730
                              + y = 170
                            }
                          + play     = "https://twilio-service-4854.twil.io/G2TFRToS.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "InflightMessage-F"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "check_before_queue"
                      + properties  = {
                          + environment_sid = "ZEf8ce7107c3db8823a53edc59e628946f"
                          + function_sid    = "ZH95bed62f9c0af98771e01cba4bd86d1f"
                          + offset          = {
                              + x = 70
                              + y = 760
                            }
                          + parameters      = [
                              + {
                                  + key   = "workspaceSid"
                                  + value = "WSf2e3f00412fa8cc45f4318b45a870ea5"
                                },
                              + {
                                  + key   = "taskQueueSid"
                                  + value = "WQe831ab19f57512b0fbcd3e4228df099e"
                                },
                            ]
                          + service_sid     = "ZS052e3d62a635572170cfbff86fb1ce1d"
                          + url             = "https://twilio-service-4854.twil.io/check_counsellors"
                        }
                      + transitions = [
                          + {
                              + event = "success"
                              + next  = "split_counsellors"
                            },
                          + {
                              + event = "fail"
                              + next  = "sendToQ6002_French"
                            },
                        ]
                      + type        = "run-function"
                    },
                  + {
                      + name        = "split_queues_2"
                      + properties  = {
                          + input  = "{{widgets.FrSwitchEnglish.Digits}}"
                          + offset = {
                              + x = 240
                              + y = 1410
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "set_retry_fr_2"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{widgets.FrSwitchEnglish.Digits}}",
                                        ]
                                      + friendly_name = "If value equal_to 1"
                                      + type          = "equal_to"
                                      + value         = "1"
                                    },
                                ]
                              + event      = "match"
                              + next       = "sendToQ6001_English"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "FrSwitchEnglish"
                      + properties  = {
                          + finish_on_key    = "#"
                          + gather_language  = "en"
                          + language         = "fr-CA"
                          + loop             = 1
                          + offset           = {
                              + x = 560
                              + y = 1200
                            }
                          + play             = "https://twilio-service-4854.twil.io/FrSwitchEnglish.mp3"
                          + profanity_filter = "true"
                          + speech_timeout   = "auto"
                          + stop_gather      = true
                          + timeout          = 2
                        }
                      + transitions = [
                          + {
                              + event = "keypress"
                              + next  = "split_queues_2"
                            },
                          + {
                              + event = "speech"
                            },
                          + {
                              + event = "timeout"
                            },
                        ]
                      + type        = "gather-input-on-call"
                    },
                  + {
                      + name        = "split_counsellors"
                      + properties  = {
                          + input  = "{{widgets.check_before_queue.parsed.totalCounsellors}}"
                          + offset = {
                              + x = -60
                              + y = 950
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "sendToQ6002_French"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{widgets.check_before_queue.parsed.totalCounsellors}}",
                                        ]
                                      + friendly_name = "If value equal_to 0"
                                      + type          = "equal_to"
                                      + value         = "0"
                                    },
                                ]
                              + event      = "match"
                              + next       = "FrSwitchEnglish"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "set_retry_fr_2"
                      + properties  = {
                          + offset    = {
                              + x = 520
                              + y = 1760
                            }
                          + variables = [
                              + {
                                  + key   = "retry_counter_2"
                                  + value = "{% if flow.variables.retry_counter_2%} {{flow.variables.retry_counter_2| plus: 1}} {% else %} 1 {% endif %}"
                                },
                            ]
                        }
                      + transitions = [
                          + {
                              + event = "next"
                              + next  = "split_retry"
                            },
                        ]
                      + type        = "set-variables"
                    },
                  + {
                      + name        = "split_retry"
                      + properties  = {
                          + input  = "{{flow.variables.retry_counter_2}}"
                          + offset = {
                              + x = 800
                              + y = 1980
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "fr_disconnect_2"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{flow.variables.retry_counter_2}}",
                                        ]
                                      + friendly_name = "If value less_than 3"
                                      + type          = "less_than"
                                      + value         = "3"
                                    },
                                ]
                              + event      = "match"
                              + next       = "fr_invalid_2"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "fr_invalid_2"
                      + properties  = {
                          + loop   = 1
                          + offset = {
                              + x = 1340
                              + y = 1760
                            }
                          + play   = "https://twilio-service-4854.twil.io/FrInvalid.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "FrSwitchEnglish"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "fr_disconnect_2"
                      + properties  = {
                          + loop   = 1
                          + offset = {
                              + x = 820
                              + y = 2250
                            }
                          + play   = "https://twilio-service-4854.twil.io/FrDisconnect.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "invalid_en"
                      + properties  = {
                          + loop   = 1
                          + offset = {
                              + x = -2800
                              + y = 920
                            }
                          + play   = "https://twilio-service-4854.twil.io/EnInvalid.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "Msg10006E-InfoMessage2"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "en_set_retry"
                      + properties  = {
                          + offset    = {
                              + x = -2450
                              + y = 420
                            }
                          + variables = [
                              + {
                                  + key   = "retry_counter"
                                  + value = "{% if flow.variables.retry_counter%} {{flow.variables.retry_counter| plus: 1}} {% else %} 1 {% endif %}"
                                },
                            ]
                        }
                      + transitions = [
                          + {
                              + event = "next"
                              + next  = "en_split_retry"
                            },
                        ]
                      + type        = "set-variables"
                    },
                  + {
                      + name        = "en_split_retry"
                      + properties  = {
                          + input  = "{{flow.variables.retry_counter}}"
                          + offset = {
                              + x = -2570
                              + y = 670
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "en_disconnect"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{flow.variables.retry_counter}}",
                                        ]
                                      + friendly_name = "If value less_than 3"
                                      + type          = "less_than"
                                      + value         = "3"
                                    },
                                ]
                              + event      = "match"
                              + next       = "invalid_en"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "en_disconnect"
                      + properties  = {
                          + loop   = 1
                          + offset = {
                              + x = -2420
                              + y = 950
                            }
                          + play   = "https://twilio-service-4854.twil.io/EnDisconnect.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "set_retry_fr"
                      + properties  = {
                          + offset    = {
                              + x = 720
                              + y = 520
                            }
                          + variables = [
                              + {
                                  + key   = "retry_counter"
                                  + value = "{% if flow.variables.retry_counter%} {{flow.variables.retry_counter| plus: 1}} {% else %} 1 {% endif %}"
                                },
                            ]
                        }
                      + transitions = [
                          + {
                              + event = "next"
                              + next  = "split_retry_fr"
                            },
                        ]
                      + type        = "set-variables"
                    },
                  + {
                      + name        = "split_retry_fr"
                      + properties  = {
                          + input  = "{{flow.variables.retry_counter}}"
                          + offset = {
                              + x = 1030
                              + y = 760
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "fr_disconnect"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{flow.variables.retry_counter}}",
                                        ]
                                      + friendly_name = "If value less_than 3"
                                      + type          = "less_than"
                                      + value         = "3"
                                    },
                                ]
                              + event      = "match"
                              + next       = "fr_invalid"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "fr_invalid"
                      + properties  = {
                          + loop   = 1
                          + offset = {
                              + x = 1500
                              + y = 640
                            }
                          + play   = "https://twilio-service-4854.twil.io/FrInvalid.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                              + next  = "Msg10006F-InfoMessage2"
                            },
                        ]
                      + type        = "say-play"
                    },
                  + {
                      + name        = "fr_disconnect"
                      + properties  = {
                          + loop   = 1
                          + offset = {
                              + x = 1090
                              + y = 1030
                            }
                          + play   = "https://twilio-service-4854.twil.io/FrDisconnect.mp3"
                        }
                      + transitions = [
                          + {
                              + event = "audioComplete"
                            },
                        ]
                      + type        = "say-play"
                    },
                ]
            }
        )
      + friendly_name  = "G2tns Studio Flow"
      + id             = (known after apply)
      + sid            = (known after apply)
      + status         = "published"
    }

  # module.channel.twilio_studio_flows_v2.channel_studio_flow["g2ton"] will be updated in-place
  ~ resource "twilio_studio_flows_v2" "channel_studio_flow" {
      ~ definition     = jsonencode(
          ~ {
              ~ states        = [
                    # (25 unchanged elements hidden)
                    {
                        name        = "split_retry"
                        properties  = {
                            input  = "{{flow.variables.retry_counter_2}}"
                            offset = {
                                x = 800
                                y = 1980
                            }
                        }
                        transitions = [
                            {
                                event = "noMatch"
                                next  = "fr_disconnect_2"
                            },
                            {
                                conditions = [
                                    {
                                        arguments     = [
                                            "{{flow.variables.retry_counter_2}}",
                                        ]
                                        friendly_name = "If value less_than 3"
                                        type          = "less_than"
                                        value         = "3"
                                    },
                                ]
                                event      = "match"
                                next       = "fr_invalid_2"
                            },
                        ]
                        type        = "split-based-on"
                    },
                  ~ {
                        name        = "cyara_test"
                      ~ properties  = {
                          ~ loop   = 50 -> 2
                            # (2 unchanged elements hidden)
                        }
                        # (2 unchanged elements hidden)
                    },
                    {
                        name        = "Copy_of_cyara_test"
                        properties  = {
                            loop   = 2
                            offset = {
                                x = 1110
                                y = 170
                            }
                            play   = "https://twilio-service-4854.twil.io/cyara-vq-testaudio.wav"
                        }
                        transitions = [
                            {
                                event = "audioComplete"
                            },
                        ]
                        type        = "say-play"
                    },
                    # (14 unchanged elements hidden)
                ]
                # (3 unchanged elements hidden)
            }
        )
        id             = "FWa695cf75e13526e93c271d161645447b"
        # (4 unchanged attributes hidden)
    }

  # module.channel.twilio_studio_flows_v2.channel_studio_flow["webchat"] will be updated in-place
  ~ resource "twilio_studio_flows_v2" "channel_studio_flow" {
      ~ definition    = jsonencode(
          ~ {
              ~ states        = [
                    # (34 unchanged elements hidden)
                    {
                        name        = "chat_hours_en"
                        properties  = {
                            environment_sid = "ZE56ef3f078fe4b40ad57d4d4f63652210"
                            function_sid    = "ZH77510a142c7bad7449d04e415b6c8187"
                            offset          = {
                                x = -50
                                y = -500
                            }
                            parameters      = [
                                {
                                    key   = "channel"
                                    value = "webchat"
                                },
                                {
                                    key   = "includeMessageTextInResponse"
                                    value = "true"
                                },
                                {
                                    key   = "language"
                                    value = "en-CA"
                                },
                            ]
                            service_sid     = "ZS2035e3023773cf7a1a482950df4f2150"
                            url             = "https://serverless-3836-production.twil.io/operatingHours"
                        }
                        transitions = [
                            {
                                event = "success"
                                next  = "hours_split_en"
                            },
                            {
                                event = "fail"
                            },
                        ]
                        type        = "run-function"
                    },
                  ~ {
                        name        = "hours_split_en"
                      ~ transitions = [
                          ~ {
                              ~ next  = "check_queue_en" -> "check_counsellors_en"
                                # (1 unchanged element hidden)
                            },
                          ~ {
                              ~ next       = "check_queue_en" -> "check_counsellors_en"
                                # (2 unchanged elements hidden)
                            },
                            {
                                conditions = [
                                    {
                                        arguments     = [
                                            "{{widgets.chat_hours_en.parsed.status}}",
                                        ]
                                        friendly_name = "If value contains closed"
                                        type          = "contains"
                                        value         = "closed"
                                    },
                                ]
                                event      = "match"
                                next       = "send_closed"
                            },
                            # (1 unchanged element hidden)
                        ]
                        # (2 unchanged elements hidden)
                    },
                    {
                        name        = "send_closed"
                        properties  = {
                            body    = "{{widgets.chat_hours_en.parsed.message}}"
                            channel = "{{trigger.message.ChannelSid}}"
                            from    = "System"
                            offset  = {
                                x = -1380
                                y = -220
                            }
                            service = "{{trigger.message.InstanceSid}}"
                            to      = "{{contact.channel.address}}"
                        }
                        transitions = [
                            {
                                event = "sent"
                            },
                            {
                                event = "failed"
                            },
                        ]
                        type        = "send-message"
                    },
                    {
                        name        = "chat_hours_fr"
                        properties  = {
                            environment_sid = "ZE56ef3f078fe4b40ad57d4d4f63652210"
                            function_sid    = "ZH77510a142c7bad7449d04e415b6c8187"
                            offset          = {
                                x = 690
                                y = -410
                            }
                            parameters      = [
                                {
                                    key   = "channel"
                                    value = "webchat"
                                },
                                {
                                    key   = "includeMessageTextInResponse"
                                    value = "true"
                                },
                                {
                                    key   = "language"
                                    value = "fr-CA"
                                },
                            ]
                            service_sid     = "ZS2035e3023773cf7a1a482950df4f2150"
                            url             = "https://serverless-3836-production.twil.io/operatingHours"
                        }
                        transitions = [
                            {
                                event = "success"
                                next  = "hours_split_fr"
                            },
                            {
                                event = "fail"
                            },
                        ]
                        type        = "run-function"
                    },
                  ~ {
                        name        = "hours_split_fr"
                      ~ transitions = [
                          ~ {
                              ~ next  = "check_queue_fr" -> "check_counsellors_fr"
                                # (1 unchanged element hidden)
                            },
                          ~ {
                              ~ next       = "check_queue_fr" -> "check_counsellors_fr"
                                # (2 unchanged elements hidden)
                            },
                            {
                                conditions = [
                                    {
                                        arguments     = [
                                            "{{widgets.chat_hours_en.parsed.status}}",
                                        ]
                                        friendly_name = "If value contains closed"
                                        type          = "contains"
                                        value         = "closed"
                                    },
                                ]
                                event      = "match"
                                next       = "send_closed_fr"
                            },
                            # (1 unchanged element hidden)
                        ]
                        # (2 unchanged elements hidden)
                    },
                    {
                        name        = "send_closed_fr"
                        properties  = {
                            body    = "{{widgets.check_hours_fr.parsed.message}}"
                            channel = "{{trigger.message.ChannelSid}}"
                            from    = "Système"
                            offset  = {
                                x = 1640
                                y = -50
                            }
                            service = "{{trigger.message.InstanceSid}}"
                            to      = "{{contact.channel.address}}"
                        }
                        transitions = [
                            {
                                event = "sent"
                            },
                            {
                                event = "failed"
                            },
                        ]
                        type        = "send-message"
                    },
                  + {
                      + name        = "check_counsellors_fr"
                      + properties  = {
                          + environment_sid = "ZEf8ce7107c3db8823a53edc59e628946f"
                          + function_sid    = "ZH95bed62f9c0af98771e01cba4bd86d1f"
                          + offset          = {
                              + x = 1560
                              + y = -200
                            }
                          + parameters      = [
                              + {
                                  + key   = "workspaceSid"
                                  + value = "WSf2e3f00412fa8cc45f4318b45a870ea5"
                                },
                              + {
                                  + key   = "taskQueueSid"
                                  + value = "WQ43733e6ff913f64edafb10b041804c6e"
                                },
                            ]
                          + service_sid     = "ZS052e3d62a635572170cfbff86fb1ce1d"
                          + url             = "https://twilio-service-4854.twil.io/check_counsellors"
                        }
                      + transitions = [
                          + {
                              + event = "success"
                              + next  = "fr_counsellors"
                            },
                          + {
                              + event = "fail"
                              + next  = "check_queue_fr"
                            },
                        ]
                      + type        = "run-function"
                    },
                  + {
                      + name        = "fr_counsellors"
                      + properties  = {
                          + input  = "{{widgets.check_counsellors_fr.parsed.totalCounsellors}}"
                          + offset = {
                              + x = 1680
                              + y = 80
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "send_queue_full_fr"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{widgets.check_counsellors_fr.parsed.totalCounsellors}}",
                                        ]
                                      + friendly_name = "If value greater_than 0"
                                      + type          = "greater_than"
                                      + value         = "0"
                                    },
                                ]
                              + event      = "match"
                              + next       = "check_queue_fr"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                  + {
                      + name        = "check_counsellors_en"
                      + properties  = {
                          + environment_sid = "ZEf8ce7107c3db8823a53edc59e628946f"
                          + function_sid    = "ZH95bed62f9c0af98771e01cba4bd86d1f"
                          + offset          = {
                              + x = -810
                              + y = -210
                            }
                          + parameters      = [
                              + {
                                  + key   = "workspaceSid"
                                  + value = "WSf2e3f00412fa8cc45f4318b45a870ea5"
                                },
                              + {
                                  + key   = "taskQueueSid"
                                  + value = "WQf659c270357487d2372a657b649a3a7a"
                                },
                            ]
                          + service_sid     = "ZS052e3d62a635572170cfbff86fb1ce1d"
                          + url             = "https://twilio-service-4854.twil.io/check_counsellors"
                        }
                      + transitions = [
                          + {
                              + event = "success"
                              + next  = "en_counsellors"
                            },
                          + {
                              + event = "fail"
                              + next  = "check_queue_en"
                            },
                        ]
                      + type        = "run-function"
                    },
                  + {
                      + name        = "en_counsellors"
                      + properties  = {
                          + input  = "{{widgets.check_counsellors_en.parsed.totalCounsellors}}"
                          + offset = {
                              + x = -940
                              + y = -10
                            }
                        }
                      + transitions = [
                          + {
                              + event = "noMatch"
                              + next  = "send_queue_full_en"
                            },
                          + {
                              + conditions = [
                                  + {
                                      + arguments     = [
                                          + "{{widgets.check_counsellors_en.parsed.totalCounsellors}}",
                                        ]
                                      + friendly_name = "If value greater_than 0"
                                      + type          = "greater_than"
                                      + value         = "0"
                                    },
                                ]
                              + event      = "match"
                              + next       = "check_queue_en"
                            },
                        ]
                      + type        = "split-based-on"
                    },
                ]
                # (3 unchanged elements hidden)
            }
        )
        id            = "FWa86857692f3ca8d027d671e8ec3125c6"
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 2 to change, 0 to destroy.

**Comment by dee-luo** [comment]
@janorivera Changes LGTM! Confirmed TaskRouter, G2TON, and webchat changes are good to go and I will confirm/test once applied, new G2TNS flow will not be hooked up yet and will go through a round of testing this week.

**Comment by janorivera** [comment]
@robert-bo-davis or @stephenhand 
This has been applied and tested last Friday on staging.
Dee will look and approve the changes on provision and configure.
For the production apply though, could I get from any of you a review and approval if everything looks OK? thanks!

**Review by robert-bo-davis — APPROVED** [review]
LGTM

**Pull request merged**
