### PR TITLE
Terragrunt Migration ET Production

### PR DESCRIPTION
**Pull request by janorivera**
Primary reviewer:

### Checklist

- [x]  Modify *.hcl files.
- [x]  Running setup-new-environment
- [x]  Importing missing AWS and Twilio resources
- [x]  Running plan for provision/configure stages.
- [x]  Running apply for provision/configure stages.
- [x]  Testing functionality

### Related Issues
Fixes #....

### CODE REVIEW

**Comment by janorivera** [comment]
## ET PROD PROVISION PLAN
[ET Provision plan.txt](https://github.com/techmatters/flex-plugins/files/13288432/ET.Provision.plan.txt)

**Comment by janorivera** [comment]
## ET PROD CONFIGURE PLAN

[ET configure plan.txt](https://github.com/techmatters/flex-plugins/files/13288497/ET.configure.plan.txt)

**Review by robert-bo-davis — APPROVED** [review]
LGTM!

**Comment by janorivera** [comment]
## CONFIGURE PLAN

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

**Comment by janorivera** [comment]
## PROVISION PLAN

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.taskRouter.twilio_taskrouter_workspaces_workflows_v1.workflow["master"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_workflows_v1" "workflow" {
      ~ configuration            = jsonencode( # whitespace changes
            {
                task_routing = {
                    filters = [
                        {
                            expression           = "channelType=='web' AND e2eTestMode=='true'"
                            filter_friendly_name = "E2E Test"
                            targets              = [
                                {
                                    expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                    queue      = "WQe7d8d1ebe612e1bc3f62185b3668dccc"
                                },
                            ]
                        },
                        {
                            expression           = "channelType =='web'  OR isContactlessTask == true"
                            filter_friendly_name = "Adama Child Helpline"
                            targets              = [
                                {
                                    expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                    queue      = "WQ9f712bd085f8c9456657828c413e3cf9"
                                },
                            ]
                        },
                    ]
                }
            }
        )
        id                       = "WSaad53380bda35319217d4fe979947c1f/WWd6da15a05e87e5f987261e279c1d18e1"
        # (4 unchanged attributes hidden)
    }

  # module.taskRouter.twilio_taskrouter_workspaces_workflows_v1.workflow["survey"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_workflows_v1" "workflow" {
      ~ configuration            = jsonencode( # whitespace changes
            {
                task_routing = {
                    filters = [
                        {
                            expression           = "isChatCaptureControl==true"
                            filter_friendly_name = "CaptureChannel"
                            targets              = [
                                {
                                    queue = "WQ6b02a13dcbe222229e6374f37a96d03c"
                                },
                            ]
                        },
                    ]
                }
            }
        )
        id                       = "WSaad53380bda35319217d4fe979947c1f/WW81ddce6ac1973f0b3a5cb1c85b1d3ccc"
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

**Review by robert-bo-davis — APPROVED** [review]
LGTM

**Pull request merged**
