### PR TITLE
Dee CA Mainline Updates

### PR DESCRIPTION
**Pull request by dee-luo**
-Final set of queue naming
-Final set of taskrouter workflows
-Updated phone numbers on Stg + Prod
-Last minute updates to G2TNS flow to put in menu message :(

### CODE REVIEW

**Comment by janorivera** [comment]
PLAN FOR PROVISION STAGE
Terraform will perform the following actions:

  # module.aws.aws_s3_bucket_lifecycle_configuration.hrm_export_expiry will be created
  + resource "aws_s3_bucket_lifecycle_configuration" "hrm_export_expiry" {
      + bucket = "tl-aselo-docs-ca-production"
      + id     = (known after apply)

      + rule {
          + id     = "HRM Exported Data Expiration Policy"
          + status = "Enabled"

          + expiration {
              + days                         = 30
              + expired_object_delete_marker = (known after apply)
            }

          + filter {
              + prefix = "hrm-data/"
            }
        }
    }

  # module.aws.aws_ssm_parameter.main_group["CHAT_WORKFLOW_SID"] must be replaced
-/+ resource "aws_ssm_parameter" "main_group" {
      ~ arn            = "arn:aws:ssm:us-east-1:712893914485:parameter/PROD_TWILIO_CA_CHAT_WORKFLOW_SID" -> (known after apply)
      ~ data_type      = "text" -> (known after apply)
      ~ description    = "Twilio account - Chat transfer workflow SID" -> (known after apply)
      ~ id             = "PROD_TWILIO_CA_CHAT_WORKFLOW_SID" -> (known after apply)
      + insecure_value = (known after apply)
      ~ key_id         = "alias/aws/ssm" -> (known after apply)
      ~ name           = "PROD_TWILIO_CA_CHAT_WORKFLOW_SID" # forces replacement -> (known after apply) # forces replacement
      - tags           = {} -> null
      ~ tags_all       = {} -> (known after apply)
      ~ tier           = "Standard" -> (known after apply)
      ~ value          = (sensitive value)
      ~ version        = 1 -> (known after apply)
        # (1 unchanged attribute hidden)
    }

  # module.aws.aws_ssm_parameter.twilio_chat_workflow_sid will be updated in-place
  ~ resource "aws_ssm_parameter" "twilio_chat_workflow_sid" {
        id             = "/production/twilio/AC9f951863c83dc61cf94bdc12a12270a5/chat_workflow_sid"
      + insecure_value = (known after apply)
        name           = "/production/twilio/AC9f951863c83dc61cf94bdc12a12270a5/chat_workflow_sid"
        tags           = {
            "Environment" = "production"
            "Name"        = "/production/twilio/AC9f951863c83dc61cf94bdc12a12270a5/chat_workflow_sid"
            "Terraform"   = "true"
        }
      ~ value          = (sensitive value)
      ~ version        = 1 -> (known after apply)
        # (7 unchanged attributes hidden)
    }

  # module.taskRouter.twilio_taskrouter_workspaces_task_queues_v1.task_queue["e2e_test"] will be created
  + resource "twilio_taskrouter_workspaces_task_queues_v1" "task_queue" {
      + assignment_activity_sid  = (known after apply)
      + friendly_name            = "E2E Test Queue"
      + id                       = (known after apply)
      + max_reserved_workers     = (known after apply)
      + reservation_activity_sid = (known after apply)
      + sid                      = (known after apply)
      + target_workers           = "email=='[aselo-alerts+production@techmatters.org](mailto:aselo-alerts%2Bproduction@techmatters.org)'"
      + task_order               = (known after apply)
      + workspace_sid            = "WSf2e3f00412fa8cc45f4318b45a870ea5"
    }

  # module.taskRouter.twilio_taskrouter_workspaces_task_queues_v1.task_queue["hc_en"] will be created
  + resource "twilio_taskrouter_workspaces_task_queues_v1" "task_queue" {
      + assignment_activity_sid  = (known after apply)
      + friendly_name            = "Health Canada English"
      + id                       = (known after apply)
      + max_reserved_workers     = (known after apply)
      + reservation_activity_sid = (known after apply)
      + sid                      = (known after apply)
      + target_workers           = "routing.skills HAS 'HCENG'"
      + task_order               = (known after apply)
      + workspace_sid            = "WSf2e3f00412fa8cc45f4318b45a870ea5"
    }

  # module.taskRouter.twilio_taskrouter_workspaces_task_queues_v1.task_queue["hc_fr"] will be created
  + resource "twilio_taskrouter_workspaces_task_queues_v1" "task_queue" {
      + assignment_activity_sid  = (known after apply)
      + friendly_name            = "Health Canada French"
      + id                       = (known after apply)
      + max_reserved_workers     = (known after apply)
      + reservation_activity_sid = (known after apply)
      + sid                      = (known after apply)
      + target_workers           = "routing.skills HAS 'HCFR'"
      + task_order               = (known after apply)
      + workspace_sid            = "WSf2e3f00412fa8cc45f4318b45a870ea5"
    }

  # module.taskRouter.twilio_taskrouter_workspaces_task_queues_v1.task_queue["health_canada_en"] will be destroyed
  # (because key ["health_canada_en"] is not in for_each map)
  - resource "twilio_taskrouter_workspaces_task_queues_v1" "task_queue" {
      - friendly_name        = "Health Canada English" -> null
      - id                   = "WSf2e3f00412fa8cc45f4318b45a870ea5/WQfd41526c4a3bf2d1ff70826e38e6ec69" -> null
      - max_reserved_workers = 1 -> null
      - sid                  = "WQfd41526c4a3bf2d1ff70826e38e6ec69" -> null
      - target_workers       = "routing.skills HAS 'HCENG'" -> null
      - task_order           = "FIFO" -> null
      - workspace_sid        = "WSf2e3f00412fa8cc45f4318b45a870ea5" -> null
    }

  # module.taskRouter.twilio_taskrouter_workspaces_task_queues_v1.task_queue["health_canada_fr"] will be destroyed
  # (because key ["health_canada_fr"] is not in for_each map)
  - resource "twilio_taskrouter_workspaces_task_queues_v1" "task_queue" {
      - friendly_name        = "Health Canada French" -> null
      - id                   = "WSf2e3f00412fa8cc45f4318b45a870ea5/WQ45f47086bab9cb8c5923882bd0d2bf50" -> null
      - max_reserved_workers = 1 -> null
      - sid                  = "WQ45f47086bab9cb8c5923882bd0d2bf50" -> null
      - target_workers       = "routing.skills HAS 'HCFR'" -> null
      - task_order           = "FIFO" -> null
      - workspace_sid        = "WSf2e3f00412fa8cc45f4318b45a870ea5" -> null
    }

  # module.taskRouter.twilio_taskrouter_workspaces_task_queues_v1.task_queue["indigenous"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_task_queues_v1" "task_queue" {
      ~ friendly_name        = "Indigenous [Interpreter]" -> "Indigenous/Interpreter"
        id                   = "WSf2e3f00412fa8cc45f4318b45a870ea5/WQ9b052e6f56db438435b63805dd85e6cb"
      ~ target_workers       = "routing.skills HAS 'Indigenous [Interpreter]'" -> "routing.skills HAS 'Indigenous/Interpreter'"
        # (4 unchanged attributes hidden)
    }

  # module.taskRouter.twilio_taskrouter_workspaces_task_queues_v1.task_queue["interpreter_en"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_task_queues_v1" "task_queue" {
      ~ friendly_name        = "Interpreter" -> "KHP Interpreter"
        id                   = "WSf2e3f00412fa8cc45f4318b45a870ea5/WQa7219cf431a904bf6cef104b8e1c7cf7"
      ~ target_workers       = "routing.skills HAS 'Interpreter' " -> "routing.skills HAS 'KHP Interpreter' "
        # (4 unchanged attributes hidden)
    }

  # module.taskRouter.twilio_taskrouter_workspaces_task_queues_v1.task_queue["interpreter_fr"] will be created
  + resource "twilio_taskrouter_workspaces_task_queues_v1" "task_queue" {
      + assignment_activity_sid  = (known after apply)
      + friendly_name            = "French Interpreter"
      + id                       = (known after apply)
      + max_reserved_workers     = (known after apply)
      + reservation_activity_sid = (known after apply)
      + sid                      = (known after apply)
      + target_workers           = "routing.skills HAS 'French Interpreter' "
      + task_order               = (known after apply)
      + workspace_sid            = "WSf2e3f00412fa8cc45f4318b45a870ea5"
    }

  # module.taskRouter.twilio_taskrouter_workspaces_workflows_v1.workflow["master"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_workflows_v1" "workflow" {
      ~ configuration            = jsonencode(
            {
              - task_routing = {
                  - filters = [
                      - {
                          - expression           = "flexOutboundDialerTargetWorker != null"
                          - filter_friendly_name = "Dialpad"
                          - targets              = [
                              - {
                                  - expression = "task.flexOutboundDialerTargetWorker == worker.contact_uri"
                                  - queue      = "WQ9360fa79f63cff7b430276d36cc29bff"
                                },
                            ]
                        },
                      - {
                          - expression           = "(to IN ['+18252547345'] AND language CONTAINS \"en-CA\") OR isContactlessTask == true"
                          - filter_friendly_name = "KHP English"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQ90d837f52891cf3768fec19069da9b2f"
                                },
                            ]
                        },
                      - {
                          - expression           = "(to IN ['+18252547345'] AND language CONTAINS \"fr-CA\")"
                          - filter_friendly_name = "KHP French"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQ4e3db3fbbeb2321e22dfdbf7a703d1a6"
                                  - timeout    = 20
                                },
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - priority   = 0
                                  - queue      = "WQ90d837f52891cf3768fec19069da9b2f"
                                  - timeout    = 0
                                },
                            ]
                        },
                      - {
                          - expression           = "(to IN ['+18252547345'] AND language CONTAINS \"en-CA\")"
                          - filter_friendly_name = "Interpreter"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQa7219cf431a904bf6cef104b8e1c7cf7"
                                },
                            ]
                        },
                      - {
                          - expression           = "(to IN ['+13656546095', '+13656546120'] AND language CONTAINS \"en-CA\")"
                          - filter_friendly_name = "G2T ON English"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQc774f3a1d09a93ae8eaba80be323e600"
                                },
                            ]
                        },
                      - {
                          - expression           = "(to IN ['+13656546095', '+13656546120'] AND language CONTAINS \"fr-CA\")"
                          - filter_friendly_name = "G2T ON French"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQ61ef6d908e82fe48bb90bd259099260e"
                                },
                            ]
                        },
                      - {
                          - expression           = "(to IN ['+13656546032', '+13656546120'])"
                          - filter_friendly_name = "G2T Interpreter"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQb003ea620f2a0d7d2fbb5049a2b24762"
                                },
                            ]
                        },
                      - {
                          - expression           = "(to IN ['+15878043655', '+15878044316'] AND language CONTAINS \"en-CA\")"
                          - filter_friendly_name = "G2T NS English"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQe4336d184540020b222d80ab28805938"
                                },
                            ]
                        },
                      - {
                          - expression           = "(to IN ['+15878043655', '+15878044316'] AND language CONTAINS \"fr-CA\")"
                          - filter_friendly_name = "G2T NS French"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQe831ab19f57512b0fbcd3e4228df099e"
                                },
                            ]
                        },
                      - {
                          - expression           = "channelType=='web' AND (language CONTAINS \"en-CA\" OR language=='')"
                          - filter_friendly_name = "Chat English"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQf659c270357487d2372a657b649a3a7a"
                                },
                            ]
                        },
                      - {
                          - expression           = "channelType=='web' AND language CONTAINS \"fr-CA\""
                          - filter_friendly_name = "Chat French"
                          - targets              = [
                              - {
                                  - expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                  - queue      = "WQ43733e6ff913f64edafb10b041804c6e"
                                },
                            ]
                        },
                    ]
                }
            }
        ) -> (known after apply)
        id                       = "WSf2e3f00412fa8cc45f4318b45a870ea5/WWf88dc2e079f1c57fb3f98753d6121b79"
        # (4 unchanged attributes hidden)
    }

Plan: 6 to add, 4 to change, 3 to destroy.

Changes to Outputs:
  ~ task_router_master_workflow_sid       = "WWf88dc2e079f1c57fb3f98753d6121b79" -> (known after apply)
  ~ task_router_workflow_sids             = {
      ~ master = "WWf88dc2e079f1c57fb3f98753d6121b79" -> (known after apply)
    }

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
Releasing state lock. This may take a few moments...

**Comment by janorivera** [comment]
PLAN FOR CONFIGURE STAGE
[CA prod plan configure stage.txt](https://github.com/techmatters/flex-plugins/files/12281391/CA.prod.plan.configure.stage.txt)

**Comment by dee-luo** [comment]
@janorivera thank you! Confirming TaskRouter changes look good to me. Not sure about the AWS changes though, @robert-bo-davis let us know if those seem ok?

**Review by robert-bo-davis — APPROVED** [review]
I am trusting that y'all have a better understanding of the studio flows than I do and have already tested. I'm only really looking at the other parts of the plan which all LGTM!

**Review by stephenhand — APPROVED** [review]
LGTM too - the plan saying the master workflow SID will change always scares me but it seems to happen in ain a lot of plans...

**Comment by robert-bo-davis** [comment]
> LGTM too - the plan saying the master workflow SID will change always scares me but it seems to happen in ain a lot of plans.

Yuuup. Yay twilio terraform provider. ;)

**Pull request merged**
