### PR TITLE
Update Facebook Flow

### PR DESCRIPTION
**Pull request by sinehome**
Updating the Facebook flow by removing the welcome message for ZW. Also adding a new offline channel to the dropdown. 

The flow update has been applied and tested in Staging, and works as intended.

### CODE REVIEW

**Comment by janorivera** [comment]
@sinehome Can you add in the description, where has these been applied (like the staging account) and if it was tested or not? and the results .
Then you'll need to tag an engineer to approve the apply to the prod account

**Comment by sinehome** [comment]
@stephenhand can you assist with a review and apply for ZW production. (See plan attached
[ZW_TF_Plan.txt](https://github.com/techmatters/flex-plugins/files/12049997/ZW_TF_Plan.txt)
)

**Comment by janorivera** [comment]
Can you confirm here if the feature flags that are currently in ZW prod match the ones in the TF file? Here are the ones that are currently set:
"enable_fullstory_monitoring": true,
            "enable_external_transcripts": true,
            "enable_upload_documents": true,
            "enable_post_survey": false,
            "enable_contact_editing": true,
            "enable_case_management": true,
            "enable_twilio_transcripts": true,
            "enable_offline_contact": true,
            "enable_filter_cases": true,
            "enable_sort_cases": true,
            "enable_transfers": true,
            "enable_manual_pulling": true,
            "enable_csam_report": false,
            "enable_csam_clc_report": false,
            "enable_canned_responses": true,
            "enable_save_insights": true,
            "enable_emoji_picker": true,
            "enable_dual_write": false,
            "post_survey_serverless_handled": true,
            "enable_voice_recordings": false,
            "enable_previous_contacts": true

**Comment by sinehome** [comment]
@janorivera I have checked and the feature flags match and are the same

**Review by stephenhand — APPROVED** [review]
LGTM - the diff was tricky to figure out but it looks ok

**Pull request merged**
