### PR TITLE
Terragrunt Migration CO Production

### PR DESCRIPTION
**Pull request by janorivera**
Primary reviewer:

### Checklist

- [x]  Updates to main.tf to use current modules
- [x]  Updates to the terraform state to match current config
- [x]  Migration done
- [x]  Apply done

### Related Issues
Fixes #....

### CODE REVIEW

**Comment by janorivera** [comment]
[CO PROD PLAN.txt](https://github.com/techmatters/flex-plugins/files/12754100/CO.PROD.PLAN.txt)

**Review by robert-bo-davis — APPROVED** [review]

**Comment by janorivera** [comment]
## PROVISION PLAN 
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.github.github_actions_secret.flex_twilio_account_sid has moved to module.github[0].github_actions_secret.flex_twilio_account_sid
    resource "github_actions_secret" "flex_twilio_account_sid" {
        id              = "flex-plugins:CO_PROD_ACCOUNT_SID"
        # (5 unchanged attributes hidden)
    }

  # module.github.github_actions_secret.flex_twilio_auth_token has moved to module.github[0].github_actions_secret.flex_twilio_auth_token
    resource "github_actions_secret" "flex_twilio_auth_token" {
        id              = "flex-plugins:CO_PROD_AUTH_TOKEN"
        # (5 unchanged attributes hidden)
    }

  # module.github.github_actions_secret.serverless_twilio_account_sid has moved to module.github[0].github_actions_secret.serverless_twilio_account_sid
    resource "github_actions_secret" "serverless_twilio_account_sid" {
        id              = "serverless:CO_PROD_ACCOUNT_SID"
        # (5 unchanged attributes hidden)
    }

  # module.github.github_actions_secret.serverless_twilio_auth_token has moved to module.github[0].github_actions_secret.serverless_twilio_auth_token
    resource "github_actions_secret" "serverless_twilio_auth_token" {
        id              = "serverless:CO_PROD_AUTH_TOKEN"
        # (5 unchanged attributes hidden)
    }

  # module.github.github_actions_secret.webchat_serverless_url has moved to module.github[0].github_actions_secret.webchat_serverless_url
    resource "github_actions_secret" "webchat_serverless_url" {
        id              = "webchat:CO_PROD_SERVERLESS_URL"
        # (5 unchanged attributes hidden)
    }

  # module.taskRouter.twilio_taskrouter_workspaces_workflows_v1.workflow["master"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_workflows_v1" "workflow" {
      ~ configuration            = jsonencode( # whitespace changes
            {
                task_routing = {
                    filters = [
                        {
                            expression           = "channelType=='web' AND e2eTestMode=='true'"
                            filter_friendly_name = "E2E Test"
                            targets              = [
                                {
                                    expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                    queue      = "WQ9d25ae2aa07307bb9db6d31315fa3bb8"
                                },
                            ]
                        },
                        {
                            expression           = "channelType =='web'  OR isContactlessTask == true OR  twilioNumber IN ['messenger:103538615719253', 'twitter:1532353002387931139', 'instagram:17841453197793547'] OR to == '+578005190690'"
                            filter_friendly_name = "Te Guío"
                            targets              = [
                                {
                                    expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                    queue      = "WQ0fd988191a9db7299964a87134aed5bc"
                                },
                            ]
                        },
                    ]
                }
            }
        )
        id                       = "WSa5ba7dde6b8a363adddb98c20977a6c3/WWd4be3258cc88a6add4e85a45fa3bf88e"
        # (4 unchanged attributes hidden)
    }

  # module.taskRouter.twilio_taskrouter_workspaces_workflows_v1.workflow["survey"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_workflows_v1" "workflow" {
      ~ configuration            = jsonencode( # whitespace changes
            {
                task_routing = {
                    filters = [
                        {
                            expression           = "isChatCaptureControl==true"
                            filter_friendly_name = "CaptureChannel"
                            targets              = [
                                {
                                    queue = "WQ54c763dc0a26c530fa1bd127a6210a5a"
                                },
                            ]
                        },
                    ]
                }
            }
        )
        id                       = "WSa5ba7dde6b8a363adddb98c20977a6c3/WW76a61a1d85743eabffd57f5aa264ab65"
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Changes to Outputs:
  + serverless_environment_production_sid = "ZE5dd6ef3cbb63cc2418c472cd51fb2d16"
  + serverless_service_sid                = "ZS70d962b047c1cd528ad2f2cae9f33b8b"
  + serverless_url                        = "https://serverless-2090-production.twil.io"
  + services_flex_chat_service_sid        = "IS090a4cf64f1e413d8a15d3f9853ac352"
  + task_router_chat_task_channel_sid     = "TC080535fc185afba233f33e407e7aa096"
  + task_router_master_workflow_sid       = "WWd4be3258cc88a6add4e85a45fa3bf88e"
  + task_router_task_channel_sids         = {
      + chat    = "TC080535fc185afba233f33e407e7aa096"
      + default = "TC39e37da166541d105bc59f5b27c23f6d"
      + email   = "TC81be9b90614c22f77093121d55a25b53"
      + sms     = "TC244e07f0c82361cc9bf63ec6b0625693"
      + survey  = "TC31054a04aeccde117ef3f4ac0a84d917"
      + video   = "TCc1c9f36188d3a8677a895647fd76b631"
      + voice   = "TC4155acd7eb622d78ae61972288d549c4"
    }
  + task_router_voice_task_channel_sid    = "TC4155acd7eb622d78ae61972288d549c4"
  + task_router_workflow_sids             = {
      + master = "WWd4be3258cc88a6add4e85a45fa3bf88e"
      + survey = "WW76a61a1d85743eabffd57f5aa264ab65"
    }

─────────────────────────────────────────────────────────────────────────────

**Comment by janorivera** [comment]
[CO PROD CONF PLAN.txt](https://github.com/techmatters/flex-plugins/files/12785020/CO.PROD.CONF.PLAN.txt)

**Review by robert-bo-davis — APPROVED** [review]
LGTM!

**Pull request merged**
