### PR TITLE
Update TaskRouter + Studio for E2E test

### PR DESCRIPTION
**Pull request by dee-luo**
-Add "Workflow Test" queue
-Update Studio sendToFlex attributes
-Update TaskRouter filters to send test chats to test queue

### CODE REVIEW

**Comment by dee-luo** [comment]
@robert-bo-davis I jumped the gun a little but this is also ready to go whenever you are ready to roll out the E2E test to KHP. Let me know how I can help test or if anything needs to be adjusted.

**Comment by dee-luo** [comment]
Updated to match naming convention used in Development (e2eTestMode). Queues are set properly as well.

**Review by robert-bo-davis — APPROVED** [review]
This has been applied to staging, but not production yet. But LGTM once it is applied to production.

**Comment by dee-luo** [comment]
@robert-bo-davis are we okay to merge this or do you want to keep this in a PR until we do the production apply? I want to start making other CA TF changes, but mindful that these changes aren't merged yet

**Pull request merged**
