### PR TITLE
Update Thailand permissions

### PR DESCRIPTION
**Pull request by annaliseirby090**
Update Thailand permissions so that case contact owners can edit any part of cases.

Per this Slack thread: https://tech-matters.slack.com/archives/CV4QM23UJ/p1712249416585439?thread_ts=1711557255.285739&cid=CV4QM23UJ

### CODE REVIEW

**Comment by annaliseirby090** [comment]
Question for @stephenhand and @janorivera : 

I also made these changes, are they necessary to get the functionality we want?

> "caseStatusTransition": [["isSupervisor"], ["isCaseContactOwner"]],
> ...
> "updateCaseContacts": [["isSupervisor"], ["isCaseContactOwner"], ["isCaseOpen"]],

**Comment by stephenhand** [comment]
> Question for @stephenhand and @janorivera :
> 
> I also made these changes, are they necessary to get the functionality we want?
> 
> > "caseStatusTransition": [["isSupervisor"], ["isCaseContactOwner"]],
> > ...
> > "updateCaseContacts": [["isSupervisor"], ["isCaseContactOwner"], ["isCaseOpen"]],

No, we should only need to add `isCaseContactOwner` equivalents for `isCreator` permissions, other permissions should remain the same

**Comment by annaliseirby090** [comment]
Ah ok thanks, that's good to know!

Should I close this PR and open a new one? Or is there a way to edit a PR? Thanks :)

**Comment by annaliseirby090** [comment]
Ok, I just removed those extra changes and pushed an update!

**Review by stephenhand — APPROVED** [review]
LGTM

**Pull request merged**
