### PR TITLE
JM MT CL Prod Plans and last edits

### PR DESCRIPTION
**Pull request by janorivera**
Primary reviewer:

## Description

Final edits and plans for JM, MT and CL PROD.

### Checklist
- [x] JM: Prod studio flow created manually. No need to apply main.tf
- [x] JM: Survey resources created manually
- [x] JM: Messaging Studio flow backed up
- [x] MT: Studio flows backed up
- [x] Enable_lex = true on all prod config files.

### JM
(Pre survey bot)

- [x] 1. Lex stage apply (creation of bots) 
- [x] 2. Manually assign flex channels to lex studio flow 
- [x] 3. Service configuration apply (turning on Lex)

### MT
(Pre survey bots)

- [x] 1. Lex stage apply (creation of bots) 
- [x] 2. MT main.tf apply (updating survey workflow filter, updating studio flows and removing FFs)
- [x] 3. Service configuration apply (turning on Lex)

### CL
(CL has only a post survey bot)

- [x] 1. Lex stage apply (creation of bots) 
- [x] 2. Provision stage apply  (updating survey workflow filter)
- [x] 3. Service configuration apply (turning on Lex)

### CODE REVIEW

**Comment by janorivera** [comment]
### JM PROD PLAN, LEX STAGE
Terraform will perform the following actions:

  # module.lex["en_JM"].aws_lex_bot.this["pre_survey"] will be created
  + resource "aws_lex_bot" "this" {
      + arn                             = (known after apply)
      + checksum                        = (known after apply)
      + child_directed                  = true
      + create_version                  = false
      + created_date                    = (known after apply)
      + description                     = "General configs/lex/en/bots Pre Survey bot"
      + detect_sentiment                = false
      + enable_model_improvements       = true
      + failure_reason                  = (known after apply)
      + id                              = (known after apply)
      + idle_session_ttl_in_seconds     = 600
      + last_updated_date               = (known after apply)
      + locale                          = "en-US"
      + name                            = "production_jm_en_JM_pre_survey"
      + nlu_intent_confidence_threshold = 0
      + process_behavior                = "BUILD"
      + status                          = (known after apply)
      + version                         = (known after apply)
      + voice_id                        = (known after apply)

      + abort_statement {
          + message {
              + content      = "Sorry, I am not able to assist at this time."
              + content_type = "PlainText"
            }
        }

      + clarification_prompt {
          + max_attempts = 2

          + message {
              + content      = <<-EOT
                    Sorry, I didn't understand that. Please try again. 
                    Please answer the questions.
                EOT
              + content_type = "PlainText"
            }
        }

      + intent {
          + intent_name    = "production_jm_en_JM_pre_survey"
          + intent_version = (known after apply)
        }
    }

  # module.lex["en_JM"].aws_lex_bot_alias.this["pre_survey"] will be created
  + resource "aws_lex_bot_alias" "this" {
      + arn               = (known after apply)
      + bot_name          = "production_jm_en_JM_pre_survey"
      + bot_version       = "$LATEST"
      + checksum          = (known after apply)
      + created_date      = (known after apply)
      + description       = "Bot alias for production_jm_en_JM_pre_survey"
      + id                = (known after apply)
      + last_updated_date = (known after apply)
      + name              = "latest"
    }

  # module.lex["en_JM"].aws_lex_intent.this["pre_survey"] will be created
  + resource "aws_lex_intent" "this" {
      + arn               = (known after apply)
      + checksum          = (known after apply)
      + create_version    = false
      + created_date      = (known after apply)
      + description       = "Helpline Specific configs/lex/en_JM/intents Pre Survey Intent Survey intent"
      + id                = (known after apply)
      + last_updated_date = (known after apply)
      + name              = "production_jm_en_JM_pre_survey"
      + sample_utterances = [
          + "Incoming webchat contact",
          + "trigger_pre_survey",
        ]
      + version           = (known after apply)

      + conclusion_statement {
          + message {
              + content      = "We'll transfer you now. Please hold for a counsellor."
              + content_type = "PlainText"
            }
        }

      + fulfillment_activity {
          + type = "ReturnIntent"
        }

      + slot {
          + description       = "Age of caller"
          + name              = "age"
          + priority          = 2
          + sample_utterances = []
          + slot_constraint   = "Required"
          + slot_type         = "production_jm_en_JM_age"
          + slot_type_version = (known after apply)

          + value_elicitation_prompt {
              + max_attempts = 2

              + message {
                  + content      = "Thank you. How old are you?"
                  + content_type = "PlainText"
                }
            }
        }
      + slot {
          + description       = "Caller is calling for self or someone else"
          + name              = "aboutSelf"
          + priority          = 1
          + sample_utterances = []
          + slot_constraint   = "Required"
          + slot_type         = "production_jm_en_JM_yes_no"
          + slot_type_version = (known after apply)

          + value_elicitation_prompt {
              + max_attempts = 2

              + message {
                  + content      = <<-EOT
                        Welcome to the helpline. To help us better serve you, please answer the following questions. You can say 'prefer not to answer' (or type X) to any question. 
                         Are you calling about yourself? Please answer Yes or No.
                    EOT
                  + content_type = "PlainText"
                }
            }
        }
      + slot {
          + description       = "Caller's gender"
          + name              = "gender"
          + priority          = 3
          + sample_utterances = []
          + slot_constraint   = "Required"
          + slot_type         = "production_jm_en_JM_gender"
          + slot_type_version = (known after apply)

          + value_elicitation_prompt {
              + max_attempts = 2

              + message {
                  + content      = "What is your gender?"
                  + content_type = "PlainText"
                }
            }
        }
      + slot {
          + description       = "Imported from question 'howDidYouKnowAboutOurLine'"
          + name              = "howDidYouKnowAboutOurLine"
          + priority          = 5
          + sample_utterances = []
          + slot_constraint   = "Required"
          + slot_type         = "production_jm_en_JM_howDidYouKnowAboutOurLine"
          + slot_type_version = (known after apply)

          + value_elicitation_prompt {
              + max_attempts = 2

              + message {
                  + content      = <<-EOT
                        How did you hear about us? Please select one: 
                         1: Advertisement 
                         2: Social Media 
                         3: SMS/Text Message 
                         4: Traditional Media 
                         5: Word of Mouth
                    EOT
                  + content_type = "PlainText"
                }
            }
        }
      + slot {
          + description       = "Imported from question 'parish'"
          + name              = "parish"
          + priority          = 4
          + sample_utterances = []
          + slot_constraint   = "Required"
          + slot_type         = "production_jm_en_JM_parish"
          + slot_type_version = (known after apply)

          + value_elicitation_prompt {
              + max_attempts = 2

              + message {
                  + content      = "What parish are you located in?"
                  + content_type = "PlainText"
                }
            }
        }
    }

  # module.lex["en_JM"].aws_lex_slot_type.this["age"] will be created
  + resource "aws_lex_slot_type" "this" {
      + checksum                 = (known after apply)
      + create_version           = false
      + created_date             = (known after apply)
      + description              = "General configs/lex/en/slot_types Age Slot Type"
      + id                       = (known after apply)
      + last_updated_date        = (known after apply)
      + name                     = "production_jm_en_JM_age"
      + value_selection_strategy = "TOP_RESOLUTION"
      + version                  = (known after apply)

      + enumeration_value {
          + synonyms = [
              + "Prefer not to answer",
              + "Rather not say",
              + "X",
              + "prefer not",
              + "prefer not to",
            ]
          + value    = "Unknown"
        }
      + enumeration_value {
          + synonyms = [
              + "eight",
            ]
          + value    = "8"
        }
      + enumeration_value {
          + synonyms = [
              + "eighteen",
            ]
          + value    = "18"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty eight",
            ]
          + value    = "88"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty five",
            ]
          + value    = "85"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty four",
            ]
          + value    = "84"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty nine",
            ]
          + value    = "89"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty one",
            ]
          + value    = "81"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty seven",
            ]
          + value    = "87"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty six",
            ]
          + value    = "86"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty three",
            ]
          + value    = "83"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty two",
            ]
          + value    = "82"
        }
      + enumeration_value {
          + synonyms = [
              + "eighty",
            ]
          + value    = "80"
        }
      + enumeration_value {
          + synonyms = [
              + "eleven",
            ]
          + value    = "11"
        }
      + enumeration_value {
          + synonyms = [
              + "fifteen",
            ]
          + value    = "15"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty eight",
            ]
          + value    = "58"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty five",
            ]
          + value    = "55"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty four",
            ]
          + value    = "54"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty nine",
            ]
          + value    = "59"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty one",
            ]
          + value    = "51"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty seven",
            ]
          + value    = "57"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty six",
            ]
          + value    = "56"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty three",
            ]
          + value    = "53"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty two",
            ]
          + value    = "52"
        }
      + enumeration_value {
          + synonyms = [
              + "fifty",
            ]
          + value    = "50"
        }
      + enumeration_value {
          + synonyms = [
              + "five",
            ]
          + value    = "5"
        }
      + enumeration_value {
          + synonyms = [
              + "forty eight",
            ]
          + value    = "48"
        }
      + enumeration_value {
          + synonyms = [
              + "forty five",
            ]
          + value    = "45"
        }
      + enumeration_value {
          + synonyms = [
              + "forty four",
            ]
          + value    = "44"
        }
      + enumeration_value {
          + synonyms = [
              + "forty nine",
            ]
          + value    = "49"
        }
      + enumeration_value {
          + synonyms = [
              + "forty one",
            ]
          + value    = "41"
        }
      + enumeration_value {
          + synonyms = [
              + "forty seven",
            ]
          + value    = "47"
        }
      + enumeration_value {
          + synonyms = [
              + "forty six",
            ]
          + value    = "46"
        }
      + enumeration_value {
          + synonyms = [
              + "forty three",
            ]
          + value    = "43"
        }
      + enumeration_value {
          + synonyms = [
              + "forty two",
            ]
          + value    = "42"
        }
      + enumeration_value {
          + synonyms = [
              + "forty",
            ]
          + value    = "40"
        }
      + enumeration_value {
          + synonyms = [
              + "four",
            ]
          + value    = "4"
        }
      + enumeration_value {
          + synonyms = [
              + "fourteen",
            ]
          + value    = "14"
        }
      + enumeration_value {
          + synonyms = [
              + "nine",
            ]
          + value    = "9"
        }
      + enumeration_value {
          + synonyms = [
              + "nineteen",
            ]
          + value    = "19"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety eight",
            ]
          + value    = "98"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety five",
            ]
          + value    = "95"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety four",
            ]
          + value    = "94"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety nine",
            ]
          + value    = "99"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety one",
            ]
          + value    = "91"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety seven",
            ]
          + value    = "97"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety six",
            ]
          + value    = "96"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety three",
            ]
          + value    = "93"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety two",
            ]
          + value    = "92"
        }
      + enumeration_value {
          + synonyms = [
              + "ninety",
            ]
          + value    = "90"
        }
      + enumeration_value {
          + synonyms = [
              + "one hundred",
            ]
          + value    = "100"
        }
      + enumeration_value {
          + synonyms = [
              + "one",
            ]
          + value    = "1"
        }
      + enumeration_value {
          + synonyms = [
              + "seven",
            ]
          + value    = "7"
        }
      + enumeration_value {
          + synonyms = [
              + "seventeen",
            ]
          + value    = "17"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy eight",
            ]
          + value    = "78"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy five",
            ]
          + value    = "75"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy four",
            ]
          + value    = "74"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy nine",
            ]
          + value    = "79"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy one",
            ]
          + value    = "71"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy seven",
            ]
          + value    = "77"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy six",
            ]
          + value    = "76"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy three",
            ]
          + value    = "73"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy two",
            ]
          + value    = "72"
        }
      + enumeration_value {
          + synonyms = [
              + "seventy",
            ]
          + value    = "70"
        }
      + enumeration_value {
          + synonyms = [
              + "six",
            ]
          + value    = "6"
        }
      + enumeration_value {
          + synonyms = [
              + "sixteen",
            ]
          + value    = "16"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty eight",
            ]
          + value    = "68"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty five",
            ]
          + value    = "65"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty four",
            ]
          + value    = "64"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty nine",
            ]
          + value    = "69"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty one",
            ]
          + value    = "61"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty seven",
            ]
          + value    = "67"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty six",
            ]
          + value    = "66"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty three",
            ]
          + value    = "63"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty two",
            ]
          + value    = "62"
        }
      + enumeration_value {
          + synonyms = [
              + "sixty",
            ]
          + value    = "60"
        }
      + enumeration_value {
          + synonyms = [
              + "ten",
            ]
          + value    = "10"
        }
      + enumeration_value {
          + synonyms = [
              + "thirteen",
            ]
          + value    = "13"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty eight",
            ]
          + value    = "38"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty five",
            ]
          + value    = "35"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty four",
            ]
          + value    = "34"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty nine",
            ]
          + value    = "39"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty one",
            ]
          + value    = "31"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty seven",
            ]
          + value    = "37"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty six",
            ]
          + value    = "36"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty three",
            ]
          + value    = "33"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty two",
            ]
          + value    = "32"
        }
      + enumeration_value {
          + synonyms = [
              + "thirty",
            ]
          + value    = "30"
        }
      + enumeration_value {
          + synonyms = [
              + "three",
            ]
          + value    = "3"
        }
      + enumeration_value {
          + synonyms = [
              + "twelve",
            ]
          + value    = "12"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty eight",
            ]
          + value    = "28"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty five",
            ]
          + value    = "25"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty four",
            ]
          + value    = "24"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty nine",
            ]
          + value    = "29"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty one",
            ]
          + value    = "21"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty seven",
            ]
          + value    = "27"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty six",
            ]
          + value    = "26"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty three",
            ]
          + value    = "23"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty two",
            ]
          + value    = "22"
        }
      + enumeration_value {
          + synonyms = [
              + "twenty",
            ]
          + value    = "20"
        }
      + enumeration_value {
          + synonyms = [
              + "two",
            ]
          + value    = "2"
        }
    }

  # module.lex["en_JM"].aws_lex_slot_type.this["gender"] will be created
  + resource "aws_lex_slot_type" "this" {
      + checksum                 = (known after apply)
      + create_version           = false
      + created_date             = (known after apply)
      + description              = "Helpline Specific helplines/jm/configs/lex/en_JM/slot_types Gender Slot Type"
      + id                       = (known after apply)
      + last_updated_date        = (known after apply)
      + name                     = "production_jm_en_JM_gender"
      + value_selection_strategy = "TOP_RESOLUTION"
      + version                  = (known after apply)

      + enumeration_value {
          + synonyms = [
              + "b",
              + "boy",
              + "m",
              + "male",
              + "man",
              + "men",
            ]
          + value    = "Male"
        }
      + enumeration_value {
          + synonyms = [
              + "don't want to say",
              + "dont want to say",
              + "i don't know",
              + "i dont know",
              + "idk",
              + "no",
              + "no thank you",
              + "prefer not",
              + "prefer not to say",
              + "x",
            ]
          + value    = "Unknown"
        }
      + enumeration_value {
          + synonyms = [
              + "f",
              + "fe",
              + "fem",
              + "female",
              + "femme",
              + "g",
              + "gal",
              + "girl",
              + "woman",
              + "women",
            ]
          + value    = "Female"
        }
    }

  # module.lex["en_JM"].aws_lex_slot_type.this["howDidYouKnowAboutOurLine"] will be created
  + resource "aws_lex_slot_type" "this" {
      + checksum                 = (known after apply)
      + create_version           = false
      + created_date             = (known after apply)
      + description              = "Helpline Specific helplines/jm/configs/lex/en_JM/slot_types howDidYouKnowAboutOurLine Slot Type"
      + id                       = (known after apply)
      + last_updated_date        = (known after apply)
      + name                     = "production_jm_en_JM_howDidYouKnowAboutOurLine"
      + value_selection_strategy = "TOP_RESOLUTION"
      + version                  = (known after apply)

      + enumeration_value {
          + synonyms = [
              + "1",
              + "1.",
              + "ad",
              + "ads",
              + "advert",
              + "adverts",
              + "from ads",
            ]
          + value    = "Advertisement"
        }
      + enumeration_value {
          + synonyms = [
              + "2",
              + "2.",
              + "facebook",
              + "fb",
              + "from facebook",
              + "from fb",
              + "from ig",
              + "from wa",
              + "from whatsapp",
              + "i saw online",
              + "ig",
              + "insta",
              + "instagram",
              + "on facebook",
              + "online",
              + "social",
              + "whatsapp",
            ]
          + value    = "Social Media"
        }
      + enumeration_value {
          + synonyms = [
              + "3",
              + "3.",
              + "from text",
              + "i got a text",
              + "sms",
              + "text",
            ]
          + value    = "SMS/Text Message"
        }
      + enumeration_value {
          + synonyms = [
              + "4",
              + "4.",
              + "from the news",
              + "media",
              + "news",
            ]
          + value    = "Traditional Media"
        }
      + enumeration_value {
          + synonyms = [
              + "5",
              + "5.",
              + "friend",
              + "from friends",
              + "from my friend",
              + "from school",
              + "i heard",
              + "my friend",
              + "school",
              + "someone told me",
            ]
          + value    = "Word of Mouth"
        }
      + enumeration_value {
          + synonyms = [
              + "dont know",
              + "i dont know",
              + "no",
              + "x",
            ]
          + value    = "Unknown"
        }
    }

  # module.lex["en_JM"].aws_lex_slot_type.this["parish"] will be created
  + resource "aws_lex_slot_type" "this" {
      + checksum                 = (known after apply)
      + create_version           = false
      + created_date             = (known after apply)
      + description              = "Helpline Specific helplines/jm/configs/lex/en_JM/slot_types parish Slot Type"
      + id                       = (known after apply)
      + last_updated_date        = (known after apply)
      + name                     = "production_jm_en_JM_parish"
      + value_selection_strategy = "TOP_RESOLUTION"
      + version                  = (known after apply)

      + enumeration_value {
          + synonyms = [
              + "andrew",
              + "s andrew",
              + "sa ndrew",
              + "st andrew",
              + "standrew",
            ]
          + value    = "St. Andrew"
        }
      + enumeration_value {
          + synonyms = [
              + "no",
              + "x",
            ]
          + value    = "Unknown"
        }
      + enumeration_value {
          + synonyms = [
              + "s ann",
              + "st ann",
              + "st.ann",
              + "sta nn",
              + "stann",
            ]
          + value    = "St. Ann"
        }
      + enumeration_value {
          + synonyms = [
              + "s catherine",
              + "sc atherine",
              + "st catherine",
              + "stcatherine",
            ]
          + value    = "St. Catherine"
        }
      + enumeration_value {
          + synonyms = [
              + "s elizabeth",
              + "se lizabeth",
              + "st elizabeth",
              + "stelizabeth",
            ]
          + value    = "St. Elizabeth"
        }
      + enumeration_value {
          + synonyms = [
              + "s james",
              + "st james",
              + "stj ames",
              + "stjames",
            ]
          + value    = "St. James"
        }
      + enumeration_value {
          + synonyms = [
              + "s mary",
              + "st mary",
              + "stm ary",
              + "stmary",
            ]
          + value    = "St. Mary"
        }
      + enumeration_value {
          + synonyms = [
              + "s thomas",
              + "st homas",
              + "st thomas",
              + "stthomas",
              + "thomas",
            ]
          + value    = "St. Thomas"
        }
      + enumeration_value {
          + synonyms = []
          + value    = "Clarendon"
        }
      + enumeration_value {
          + synonyms = []
          + value    = "Hanover"
        }
      + enumeration_value {
          + synonyms = []
          + value    = "Kingston"
        }
      + enumeration_value {
          + synonyms = []
          + value    = "Manchester"
        }
      + enumeration_value {
          + synonyms = []
          + value    = "Portland"
        }
      + enumeration_value {
          + synonyms = []
          + value    = "Trelawny"
        }
      + enumeration_value {
          + synonyms = []
          + value    = "Westmoreland"
        }
    }

  # module.lex["en_JM"].aws_lex_slot_type.this["yes_no"] will be created
  + resource "aws_lex_slot_type" "this" {
      + checksum                 = (known after apply)
      + create_version           = false
      + created_date             = (known after apply)
      + description              = "General configs/lex/en/slot_types slot type for Yes-No kind of questions"
      + id                       = (known after apply)
      + last_updated_date        = (known after apply)
      + name                     = "production_jm_en_JM_yes_no"
      + value_selection_strategy = "TOP_RESOLUTION"
      + version                  = (known after apply)

      + enumeration_value {
          + synonyms = [
              + "1",
              + "accept",
              + "y",
              + "ya",
              + "yah",
              + "yeah",
              + "yep",
              + "yes",
              + "yup",
            ]
          + value    = "Yes"
        }
      + enumeration_value {
          + synonyms = [
              + "2",
              + "n",
              + "nah",
              + "no",
              + "nope",
              + "not",
              + "reject",
            ]
          + value    = "No"
        }
    }

Plan: 8 to add, 0 to change, 0 to destroy.

**Comment by janorivera** [comment]
### JM PROD PLAN, SERVICE CONFIGURATIONS

Initializing service configuration for jm

------------------
Environment: production
Helpline Code: jm
Account SID: AC9fd261078d40fcfa06f0e374921af7a5

Plan:
Add attributes.environment with value production
Add attributes.helpline_code with value jm
Add attributes.aws_region with value us-east-1
Add attributes.feature_flags.enable_aselo_messaging_ui with value False
Add attributes.feature_flags.enable_conferencing with value False
Add attributes.feature_flags.enable_counselor_toolkits with value False
Add attributes.feature_flags.enable_csam_clc_report with value False
Add attributes.feature_flags.enable_lex with value True
Add attributes.feature_flags.enable_voice_recordings with value False
Add attributes.feature_flags.enable_transcripts with value False
Cleaning up...

**Comment by janorivera** [comment]
### MT PROD PLAN, LEX STAGE
[MT PROD PLAN LEX STAGE.txt](https://github.com/techmatters/flex-plugins/files/12338930/MT.PROD.PLAN.LEX.STAGE.txt)

### MT PROD PLAN, SERVICE CONFIGURATIONS

Initializing service configuration for mt

------------------
Environment: production
Helpline Code: mt
Account SID: AC7854f6126459347434a8e659295ebb79

Plan:
Add attributes.environment with value production
Add attributes.helpline_code with value mt
Add attributes.aws_region with value eu-west-1
Add attributes.feature_flags.enable_conferencing with value False
Add attributes.feature_flags.enable_counselor_toolkits with value False
Add attributes.feature_flags.enable_csam_clc_report with value False
Add attributes.feature_flags.enable_lex with value True
Add attributes.feature_flags.enable_voice_recordings with value False
Add attributes.feature_flags.post_survey_serverless_handled with value False
Add attributes.feature_flags.enable_transcripts with value False
Cleaning up...

**Comment by janorivera** [comment]
### CL PRODUCTION PLAN, LEX STAGE
[CL PROD PLAN LEX STAGE.txt](https://github.com/techmatters/flex-plugins/files/12339277/CL.PROD.PLAN.LEX.STAGE.txt)

### CL PRODUCTION PLAN, PROVISION STAGE

[CL PROD PLAN PROVISION STAGE.txt](https://github.com/techmatters/flex-plugins/files/12339301/CL.PROD.PLAN.PROVISION.STAGE.txt)

### CL PRODUCTION PLAN, SERVICE CONFIGURATIONS

------------------
Environment: production
Helpline Code: cl
Account SID: AC13e88b6577da29a0b35c0ea7939c3c22

Plan:
Add attributes.environment with value production
Add attributes.helpline_code with value cl
Add attributes.aws_region with value us-east-1
Add attributes.feature_flags.enable_conferencing with value False
Add attributes.feature_flags.enable_lex with value False
Add attributes.feature_flags.enable_transcripts with value False
Update attributes.feature_flags.enable_fullstory_monitoring from True to False
Cleaning up...

**Review by robert-bo-davis — APPROVED** [review]
LGTM. Update lex to true on CL. ;)

**Pull request merged**
