### PR TITLE
Alejandro co form customizations

### PR DESCRIPTION
**Pull request by janorivera**
Primary reviewer:
@Humairaa127

## Description
First version for the customizations for the Colombia setup.

### Verification steps
This should modify only files related with customizations for Te Guío (CO).

Check list

- [x] /hrm-form-definitions/form-definitions
- [x] /plugin-hrm-form/src/permissions
- [x] /plugin-hrm-form/src/translations

### CODE REVIEW

**Comment by Humairaa127** [comment]
We can remove unnecessary fields from the insights files (e.g. there are no one to many configs)

**Comment by Humairaa127** [comment]
Can we add the Did you receive consent for data capture of this contact? checkbox to the summary tab

**Review by stephenhand — APPROVED** [review]

**Comment by stephenhand** [comment]
@janorivera - Do I need to wait for more approvals on this one or can I go ahead and merge it?

**Comment by janorivera** [comment]
@stephenhand no need to wait for more! you can go ahead and merge :) Thanks!

**Pull request merged**
