### PR TITLE
edited insights mapping for Aselo demo based on new form definitions

### PR DESCRIPTION
**Pull request by joyceaselo**
@dee-luo 

Also got rid of some "village" fields in form definitions.

### CODE REVIEW

**Comment by joyceaselo** [comment]
@dee-luo
I fixed some typos in the form definitions. Let me know if this is ready to merge.

**Comment by nickhurlburt** [comment]
@joyceaselo @dee-luo should this be merged or closed?

**Comment by joyceaselo** [comment]
I think this is ready to be merged. @dee-luo please confirm.

**Comment by joyceaselo** [comment]
@nickhurlburt we are ready to merge! sorry for delay.

cc @dee-luo

**Pull request merged**
