### PR TITLE
Terragrunt migration JM Production

### PR DESCRIPTION
**Pull request by janorivera**
Primary reviewer:

### Checklist
- [x] Updates to main.tf to use current modules
- [x] Updates to the terraform state to match current config
- [x] Migration done
- [x] Apply done

### Related Issues
Fixes #....

### CODE REVIEW

**Comment by janorivera** [comment]
## JM PROD PLAN
[JM PROD PLAN.txt](https://github.com/techmatters/flex-plugins/files/12677033/JM.PROD.PLAN.txt)

**Comment by janorivera** [comment]
## PROVISION PLAN

Terraform will perform the following actions:

  # module.github[0].github_actions_secret.flex_twilio_account_sid will be created
  + resource "github_actions_secret" "flex_twilio_account_sid" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "flex-plugins"
      + secret_name     = "JM_PROD_ACCOUNT_SID"
      + updated_at      = (known after apply)
    }

  # module.github[0].github_actions_secret.flex_twilio_auth_token will be created
  + resource "github_actions_secret" "flex_twilio_auth_token" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "flex-plugins"
      + secret_name     = "JM_PROD_AUTH_TOKEN"
      + updated_at      = (known after apply)
    }

  # module.github[0].github_actions_secret.serverless_twilio_account_sid will be created
  + resource "github_actions_secret" "serverless_twilio_account_sid" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "serverless"
      + secret_name     = "JM_PROD_ACCOUNT_SID"
      + updated_at      = (known after apply)
    }

  # module.github[0].github_actions_secret.serverless_twilio_auth_token will be created
  + resource "github_actions_secret" "serverless_twilio_auth_token" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "serverless"
      + secret_name     = "JM_PROD_AUTH_TOKEN"
      + updated_at      = (known after apply)
    }

  # module.github[0].github_actions_secret.webchat_serverless_url will be created
  + resource "github_actions_secret" "webchat_serverless_url" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "webchat"
      + secret_name     = "JM_PROD_SERVERLESS_URL"
      + updated_at      = (known after apply)
    }

  # module.services.twilio_chat_services_v2.flex_chat_service will be updated in-place
  ~ resource "twilio_chat_services_v2" "flex_chat_service" {
      ~ friendly_name                              = "Flex Chat Service" -> "Flex Conversation Service"
        id                                         = "IS2f3e62ed4af84796a43e6f3787014439"
        # (21 unchanged attributes hidden)
    }

  # module.taskRouter.twilio_taskrouter_workspaces_workflows_v1.workflow["master"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_workflows_v1" "workflow" {
      ~ configuration            = jsonencode( # whitespace changes
            {
                task_routing = {
                    filters = [
                        {
                            expression           = "channelType=='web' AND e2eTestMode=='true'"
                            filter_friendly_name = "E2E Test"
                            targets              = [
                                {
                                    expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                    queue      = "WQ5a8b2e20d37b37d4493eaf7183f14f5c"
                                },
                            ]
                        },
                        {
                            expression           = "helpline=='SafeSpot' OR channelType=='web' OR to=='+14244147346' OR to=='+18767287042' OR twilioNumber=='instagram:17841444523369053' OR twilioNumber=='messenger:107246798170317'"
                            filter_friendly_name = "SafeSpot"
                            targets              = [
                                {
                                    expression = "(worker.waitingOfflineContact != true AND ((task.channelType == 'voice' AND worker.channel.chat.assigned_tasks == 0) OR (task.channelType != 'voice' AND worker.channel.voice.assigned_tasks == 0)) AND ((task.transferTargetType == 'worker' AND task.targetSid == worker.sid) OR (task.transferTargetType != 'worker' AND worker.sid != task.ignoreAgent))) OR (worker.waitingOfflineContact == true AND task.targetSid == worker.sid AND task.isContactlessTask == true)"
                                    queue      = "WQa4103558b653833e5ac4a7beff5642dc"
                                },
                            ]
                        },
                    ]
                }
            }
        )
        id                       = "WS4c9446c18e9ec8572cdc0f1a5fed82b0/WWfcce7a359778f5ab533e7345244079e0"
        # (4 unchanged attributes hidden)
    }

  # module.taskRouter.twilio_taskrouter_workspaces_workflows_v1.workflow["survey"] will be updated in-place
  ~ resource "twilio_taskrouter_workspaces_workflows_v1" "workflow" {
      ~ configuration            = jsonencode( # whitespace changes
            {
                task_routing = {
                    filters = [
                        {
                            expression           = "isChatCaptureControl==true"
                            filter_friendly_name = "CaptureChannel"
                            targets              = [
                                {
                                    queue = "WQebe874b8f4dd2e88e664970bee44af6a"
                                },
                            ]
                        },
                    ]
                }
            }
        )
        id                       = "WS4c9446c18e9ec8572cdc0f1a5fed82b0/WW096aa9a9fedf7a2926b182d909a13a19"
        # (4 unchanged attributes hidden)
    }

Plan: 5 to add, 3 to change, 0 to destroy.

Changes to Outputs:
  + serverless_environment_production_sid = "ZE471872ba9e5a44ea96c773adb2b9076c"
  + serverless_service_sid                = "ZSf7422a38f3b243b8aab97ca268f4ce6b"
  + serverless_url                        = "https://serverless-3170-production.twil.io"
  + services_flex_chat_service_sid        = "IS2f3e62ed4af84796a43e6f3787014439"
  + task_router_chat_task_channel_sid     = "TC27259d325c9ce7357756864c8bd82c54"
  + task_router_master_workflow_sid       = "WWfcce7a359778f5ab533e7345244079e0"
  + task_router_task_channel_sids         = {
      + chat    = "TC27259d325c9ce7357756864c8bd82c54"
      + default = "TCd3d90b66da557379da5feddca7e738e8"
      + email   = "TC7b7417c5d2589196b82ef3d52e7da212"
      + sms     = "TC0de8eff5827008d1d6ec946d8c5aef3c"
      + survey  = "TC4128c3aedc235b7c7a72db31d4923fbc"
      + video   = "TCe957f5460946e42f8d090b971c1c11eb"
      + voice   = "TCe28876d478d6423dcfdd4d148cd39615"
    }
  + task_router_voice_task_channel_sid    = "TCe28876d478d6423dcfdd4d148cd39615"
  + task_router_workflow_sids             = {
      + master = "WWfcce7a359778f5ab533e7345244079e0"
      + survey = "WW096aa9a9fedf7a2926b182d909a13a19"
    }

**Review by robert-bo-davis — APPROVED** [review]
LGTM once ssm param case issue is merged around.

**Comment by janorivera** [comment]
## Configure plan

No changes. Your infrastructure still matches the configuration.

Terraform has checked that the real remote objects still match the result of
your most recent changes, and found no differences.

**Comment by janorivera** [comment]
@robert-bo-davis thanks! I've imported the SSM parameter and I've executed the migrate-state process for all stages.
The plans above are for the provision and configure stages.
Should I go ahead and run apply for the provision stage?  The changes on github actions secrets are a bit unexpected, I've run in a similar situation before and for some reason it didn't fail. If it fails though then I'll need to import those resources.

**Pull request merged**
