### PR TITLE
Show Ip address on Previous Contacts banner

### PR DESCRIPTION
**Pull request by murilovmachado**
Jira: https://bugs.benetech.org/browse/CHI-630

This PR enhances the Previous Contacts Banner to show:
- IP Address or;
- Phone Number or;
- Facebook Messenger ID

image

### CODE REVIEW

**Review by nickhurlburt — APPROVED** [review]
Looks good.  One random comments from someone who hasn't been looking at the code much recently... so don't take this too seriously:  `isITalk` doesn't seem like a clear name to me. Is the goal is to distinguish between tasks we've made up vs tasks that involve an active conversation?  `isInboundTask`?  `isConversationalTask`?  Not sure.

**Comment by murilovmachado** [comment]
> Looks good. One random comments from someone who hasn't been looking at the code much recently... so don't take this too seriously: `isITalk` doesn't seem like a clear name to me. Is the goal is to distinguish between tasks we've made up vs tasks that involve an active conversation? `isInboundTask`? `isConversationalTask`? Not sure.

@nickhurlburt You're right, `isITask` is not a clear name. I was actually struggling to come with a good name. The thing is that our task type is `type CustomITask = ITask | OfflineContactTask | InMyBehalfITask;`.

We already had these two type checkers `isOfflineContactTask` and `isInMyBehalfITask`. I wanted a type checker for the first type and couldn't figure out a good name. So I've just followed the pattern as the previously existing one **is**+**Type**. But I agree the name is not descriptive enough.

I've tried `isNotOfflineContactTaskOrInMyBehalfITask` but it didn't seem a good name. And keep repeating the check as `!isOfflineContactTask(task) && !isInMyBehalfITask(task)` wasw no ideal too. So I appreciate suggestions on what would be a better name. Your suggestion `isInboundTask ` seems like a good idea. What do you think @GPaoloni ?

**Review by GPaoloni — APPROVED** [review]
Great! 
I think `isInboundTask` or `isTwilioTask` are good names.

**Comment by murilovmachado** [comment]
> Great!
> I think `isInboundTask` or `isTwilioTask` are good names.

Thanks, I think `isTwilioTask` is very clear

**Pull request merged**
