### PR TITLE
Fixed custom date show / hide behaviour

### PR DESCRIPTION
**Pull request by stephenhand**
Primary reviewer: @mmythily 

## Description

Reimplemented the show / hide behaviour on custom dates for the date filter fields

### Checklist
- [X] Corresponding issue has been opened
- N/A New tests added
- N/A Strings are localized
- [X] Tested for chat contacts
- [X] Tested for call contacts

### Related Issues
Fixes CHI-1319

### Verification steps

* Open the case list
* Apply a custom filter
* Replace the custom filter with a standard filter
* Clear filters

Verify show / hide behaviour is as expected in each case. Also verify filtering behaviour is expected

@mmythily - could you also verify I haven't introduced any styling issues that would undo the visual clean up work you did recently? Thx

### CODE REVIEW

**Comment by mythilytm** [comment]
I see that this PR is set to merge into [deploy-ed77387](https://github.com/techmatters/flex-plugins/tree/deploy-ed77387) instead of master

**Comment by nickhurlburt** [comment]
@mythilytm I would guess that Steve created that deploy branch deliberately, so that ongoing development on master is not affected.

**Comment by mythilytm** [comment]
The changes you made work great. In terms of the style change, these changes still conform to the request made by Jana:
`7. The "custom" field in the filters are showing empty white space. Can we have this white space close and open upon the user selecting "custom"? If it is too difficult technically to do, can we just always show the date fields? I would prefer not to have the white space.` - [1202](https://bugs.benetech.org/browse/CHI-1202)

**Review by mythilytm — APPROVED** [review]
Looks good to me!

**Pull request merged**
